apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: lock-unlock-
namespace: lock-unlock

# commonLabels:
#   app: lock-unlock-fuseki


resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
