apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
- name: ghcr.io/lock-unlock-testdata/fuseki:4.9.0
  newName: lock-unlock-testdata/fuseki

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: fuseki.127.0.0.1.nip.io
  # - target:
  #     kind: Ingress
  #     name: ingress
  #   patch: |
  #     - op: add
  #       path: /spec
  #       value: 
  #         ingressClassName: nginx
